/**
 * Copyright 2015 Peter Nerg
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package javascalautils;

import static javascalautils.TryCompanion.Try;

import java.io.Serializable;
import java.util.NoSuchElementException;
import java.util.function.Function;
import java.util.function.Predicate;
import java.util.function.Supplier;

/**
 * Represents the 'successful' implementation of {@link Try}. <br>
 * For examples on usage refer to the documentation for {@link Try}.
 * 
 * @author Peter Nerg
 * @since 1.0
 * @param <T>
 *            The type of the value represented by this instance
 */
public final class Success<T> implements Try<T>, Serializable {

    private static final long serialVersionUID = -5588727176438040926L;
    private final T value;

    /**
     * Creates a 'successful' instance with the provided value. <br>
     * Null values are allowed.
     * 
     * @param value
     *            The value represented by this instance
     */
    public Success(T value) {
        this.value = value;
    }

    /**
     * Always returns <code>true</code>.
     */
    @Override
    public boolean isSuccess() {
        return true;
    }

    /**
     * Returns the value provided in the constructor. <br>
     * I.e. the provided supplier is never use.
     */
    @Override
    public T getOrElse(Supplier<T> supplier) {
        return value;
    }

    /**
     * Always returns <i>this</i>. <br>
     * I.e. the provided supplier is never use.
     */
    @Override
    public Try<T> orElse(Supplier<Try<T>> supplier) {
        return this;
    }

    /**
     * Returns the value provided in the constructor.
     */
    @Override
    public T get() {
        return value;
    }

    /**
     * Returns a {@link Failure} with an {@link UnsupportedOperationException}. <br>
     * Since this is a 'success' it cannot be mapped to a 'failure'
     */
    @Override
    public Try<Throwable> failed() {
        return new Failure<>(new UnsupportedOperationException("Cannot make a Failure of a Success"));
    }

    /**
     * Applies the value to the function and returns the {@link Try} representing the mapped value.
     */
    @Override
    public <R> Try<R> map(Function<T, R> function) {
        return Try(() -> function.apply(value));
    }

    /**
     * Applies the value to the function and returns the {@link Try} generated by the function.
     * 
     * @since 1.2
     */
    @Override
    public <R> Try<R> flatMap(Function<T, Try<R>> function) {
        return function.apply(value);
    }

    /**
     * Applies the predicate to the value of this instance, if it matches <i>this</i> is returned else a {@link Failure}.
     * 
     * @since 1.4
     */
    @Override
    public Try<T> filter(Predicate<T> predicate) {
        return predicate.test(value) ? this : new Failure<>(new NoSuchElementException("Predicate did not match value, now empty result"));
    }

    /**
     * Always returns <i>this</i> . <br>
     * As per definition this is a success and will not need to be recovered.
     * 
     * @since 1.4
     */
    @Override
    public Try<T> recover(Function<Throwable, T> function) {
        return this;
    }

    /**
     * Always returns <i>this</i> . <br>
     * As per definition this is a success and will not need to be recovered.
     * 
     * @since 1.4
     */
    @Override
    public Try<T> recoverWith(Function<Throwable, Try<T>> function) {
        return this;
    }

    /**
     * Returns a String representation of the instance.
     */
    @Override
    public String toString() {
        return "Success:" + (value != null ? value.toString() : "NULL VALUE");
    }
}
